### ISSUE TITLE
新增批量添加分支功能

### ISSUE THREAD

**Issue by ColinCollins** [cocos-creator/workflows#1]
1.addRepoBranch()
新功能保留 exec => promisify 部分内容
2.增加执行功能为：
git checkout -b [new_branch_name] 新增分支
git push origin [new_branch_name]  上传远程仓库

**Comment by jareguo** [comment]
创建分支后，请将 ftp 上对应的 cocos2d-x 目录也复制出来
例如，从 dev 上创建出 v1.10 以后，需要把 ftp 把上的 cocos2d-x 的 dev 目录下的文件都复制到 v1.10 中。ftp 地址、目录和上传代码请参考 https://github.com/cocos-creator/cocos2d-x-lite/blob/644e8c2bd21b91339891a083c9efa984ff67ba01/gulpfile.js#L73

**Comment by ColinCollins** [comment]
1. addRepoBranch 方法 执行三个命令： 查看当前分支，创建新的分支并切换到新分支，上传新分支到远程仓库
2.doBranchFireballRepo 系列流程还是三个步骤：连接 fireball 远程， 创建新的分支，在 cocos2dx 远程仓库下载引擎压缩文件并解压，最后遍历关联仓库进行分支创建。
3.新增 下载方法 downloadCocos2dx() -> 调用 Download module 通过链接下载压缩文件。
当前问题：
1.cocos2dx 下载版本需要进行确定

**Comment by ColinCollins** [comment]
新增功能之后调用问题：不能直接使用 run tag ， 需要重新文件调用内容 使用 gulp scripts 命令创建多个起始命令。

**Comment by ColinCollins** [comment]
重新新建一个文件 branch.js 也可以，照搬 tag 内容

**Comment by jareguo** [comment]
该功能我已经实现了，采用的是 GitHub 的 restful API，不依赖本地 git 仓库，省去了各种 clone/解压操作，性能非常高。  https://github.com/cocos-creator/workflows/commit/32a8d3e8aa83b7d067c8d7ff6a46cc941b55e5af

**Comment by ColinCollins** [comment]
workflow 工作流的实现：
1. 本地仓库管理更加的简便化，全局式命令行操作，管理仓库将不再需要切换本地的仓库文件夹，对应远程仓库的管理。
2. 自动化流程，节省了 git 重复性操作。针对 engine 仓库，节省了下载拷贝关联引擎文件的操作。
